version: '3.8'

services:
  nextjs-app:
    build: .
    container_name: nextjs-app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - ./src/infrastructure/data:/app/src/infrastructure/data  # Persist data directory
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
